name: Run product_scraper_thread

on:
  workflow_dispatch:

jobs:
  run-thread:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install requirements
        run: pip install -r requirements_thread.txt
      - name: Run scraper (threaded)
        run: python product_scraper_thread.py